#!/bin/bash

# This script starts a Gnome Terminal with a number of tabs open
# each of which is titled for its purpose.

# It also opens Firefox with a bunch of tabs I use every day.

WORK_DIR=$1

gnome-terminal --hide-menubar \
  --tab-with-profile=Default \
  --title=VimRails \
  --working-directory=$WORK_DIR \
  --command="bash -c 'gitvi; bash'" \
  \
  --tab-with-profile=Default \
  --title=Bash \
  --working-directory=$WORK_DIR \
  \
  --tab-with-profile=Default \
  --title=PostgreSQL \
  --working-directory=$WORK_DIR \
  --command="bash -c './script/dbconsole; bash'" \
  \
  --tab-with-profile=Default \
  --title=Server \
  --working-directory=$WORK_DIR \
  --command="bash -c './script/server; bash'" \
  \
  --tab-with-profile=Default \
  --title=RailsConsole \
  --working-directory=$WORK_DIR \
  --command="bash -c './script/console; bash'" \
  \
  --tab-with-profile=Default \
  --title=DevelopmentLog \
  --working-directory=$WORK_DIR \
  --command="bash -c '/usr/bin/inotail -f log/development.log; bash'" \
  \
  --tab-with-profile=Default \
  --title=TestLog \
  --working-directory=$WORK_DIR \
  --command="bash -c '/usr/bin/inotail -f log/test.log; bash'" \
  \
  --tab-with-profile=Default \
  --title=BackgroundRbLog \
  --working-directory=$WORK_DIR \
  --command="bash -c '/usr/bin/inotail -f log/$(ls $WORK_DIR/log | grep background | grep -v debug | head -n1); bash'"

nohup firefox -new-tab http://localhost:3000 &
sleep 5
nohup firefox -new-tab http://api.rubyonrails.org &
sleep 1
nohup firefox -new-tab http://corelib.rubyonrails.org/ &
sleep 1
nohup firefox -new-tab http://stdlib.rubyonrails.org/ &
sleep 1
nohup firefox -new-tab http://pm.incontext.com.au &
sleep 1
nohup firefox -new-tab http://gmail.com &
sleep 1
nohup firefox -new-tab http://twitter.com &
sleep 1
nohup firefox -new-tab http://reader.google.com &
